// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5C9YRqdfk8ZgmusEZuSTjFbOqd3s3xUA',
    appId: '1:193627740084:web:ac8317f0930840b51484e1',
    messagingSenderId: '193627740084',
    projectId: 'fir-auth-f9191',
    authDomain: 'fir-auth-f9191.firebaseapp.com',
    storageBucket: 'fir-auth-f9191.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEhPivqYQtXY4UOWTQfvw2xXLOc9RG-Jw',
    appId: '1:193627740084:android:6e9bbbae2d9bdfd31484e1',
    messagingSenderId: '193627740084',
    projectId: 'fir-auth-f9191',
    storageBucket: 'fir-auth-f9191.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR12x9ttUsHJbBa57sNDkUUA3rC2Ud2CQ',
    appId: '1:193627740084:ios:f29c9657c8cfdcfe1484e1',
    messagingSenderId: '193627740084',
    projectId: 'fir-auth-f9191',
    storageBucket: 'fir-auth-f9191.firebasestorage.app',
    iosBundleId: 'com.example.newprojauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR12x9ttUsHJbBa57sNDkUUA3rC2Ud2CQ',
    appId: '1:193627740084:ios:f29c9657c8cfdcfe1484e1',
    messagingSenderId: '193627740084',
    projectId: 'fir-auth-f9191',
    storageBucket: 'fir-auth-f9191.firebasestorage.app',
    iosBundleId: 'com.example.newprojauth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5C9YRqdfk8ZgmusEZuSTjFbOqd3s3xUA',
    appId: '1:193627740084:web:edeaf411bdabcad51484e1',
    messagingSenderId: '193627740084',
    projectId: 'fir-auth-f9191',
    authDomain: 'fir-auth-f9191.firebaseapp.com',
    storageBucket: 'fir-auth-f9191.firebasestorage.app',
  );
}
